export const mockUser = {
  id: "user_1",
  name: "Daniel Smith",
  email: "demo@devstash.io",
  image: null,
  isPro: true,
}

export const mockItemTypes = [
  { id: "type_snippets", name: "Snippets", slug: "snippets", icon: "Code", color: "#3b82f6", category: "TEXT" as const, isSystem: true, order: 1, count: 89 },
  { id: "type_prompts", name: "Prompts", slug: "prompts", icon: "Sparkles", color: "#8b5cf6", category: "TEXT" as const, isSystem: true, order: 2, count: 33 },
  { id: "type_notes", name: "Notes", slug: "notes", icon: "StickyNote", color: "#fde047", category: "TEXT" as const, isSystem: true, order: 3, count: 27 },
  { id: "type_commands", name: "Commands", slug: "commands", icon: "Terminal", color: "#f97316", category: "TEXT" as const, isSystem: true, order: 4, count: 31 },
  { id: "type_links", name: "Links", slug: "links", icon: "Link", color: "#10b981", category: "URL" as const, isSystem: true, order: 5, count: 44 },
  { id: "type_files", name: "Files", slug: "files", icon: "File", color: "#6b7280", category: "FILE" as const, isSystem: true, order: 6, count: 0 },
  { id: "type_images", name: "Images", slug: "images", icon: "Image", color: "#ec4899", category: "FILE" as const, isSystem: true, order: 7, count: 0 },
]

export const mockItems = [
  {
    id: "item_1",
    title: "useDebounce hook",
    description: "Custom React hook for debouncing values",
    content: `export function useDebounce<T>(value: T, delay: number) {
  const [debounced, setDebounced] = useState(value);
  ...`,
    language: "typescript",
    typeId: "type_snippets",
    type: mockItemTypes[0],
    tags: [{ tag: { name: "react" } }, { tag: { name: "hooks" } }],
    isFavorite: false,
    isPinned: true,
    lastUsedAt: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    userId: "user_1",
    aiTags: [],
    collections: [],
  },
  {
    id: "item_2",
    title: "Code review prompt",
    description: "Prompt for thorough AI code review",
    content: `You are a senior engineer conducting a thorough code review. Review the following code for: security vulnerabilities, performance issues, readability...`,
    language: null,
    typeId: "type_prompts",
    type: mockItemTypes[1],
    tags: [{ tag: { name: "review" } }, { tag: { name: "claude" } }],
    isFavorite: false,
    isPinned: true,
    lastUsedAt: new Date(Date.now() - 96 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 96 * 60 * 1000).toISOString(),
    userId: "user_1",
    aiTags: [],
    collections: [],
  },
  {
    id: "item_3",
    title: "Docker compose for Postgres",
    description: "Local dev Postgres with pgAdmin",
    content: `version: '3.8'\nservices:\n  db:\n    image: postgres:16...`,
    language: "yaml",
    typeId: "type_snippets",
    type: mockItemTypes[0],
    tags: [{ tag: { name: "docker" } }, { tag: { name: "postgres" } }],
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    aiTags: [],
    collections: [],
  },
  {
    id: "item_4",
    title: "GPT system message — technical writer",
    description: "System prompt for clean technical documentation",
    content: `You are a technical writer specializing in developer documentation. Write clearly and concisely...`,
    language: null,
    typeId: "type_prompts",
    type: mockItemTypes[1],
    tags: [{ tag: { name: "gpt" } }, { tag: { name: "writing" } }],
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    aiTags: [],
    collections: [],
  },
  {
    id: "item_5",
    title: "Prisma context file",
    description: "CLAUDE.md context for Prisma schema generation",
    content: `# Prisma Context\nAlways use migrations. Never use db push...`,
    language: null,
    typeId: "type_notes",
    type: mockItemTypes[2],
    tags: [{ tag: { name: "prisma" } }, { tag: { name: "context" } }],
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    aiTags: [],
    collections: [],
  },
]

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Reusable React hooks, components, and patterns",
    isFavorite: true,
    itemCount: 34,
    defaultTypeId: "type_snippets",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    dominantColor: "#3b82f6",
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Curated prompts for GPT, Claude, and other models",
    isFavorite: true,
    itemCount: 18,
    defaultTypeId: "type_prompts",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    dominantColor: "#8b5cf6",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "CLAUDE.md and AI context files for projects",
    isFavorite: false,
    itemCount: 5,
    defaultTypeId: "type_notes",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    dominantColor: "#fde047",
  },
  {
    id: "col_4",
    name: "Dev Workflow",
    description: "Scripts, commands, and tools for daily dev work",
    isFavorite: false,
    itemCount: 21,
    defaultTypeId: "type_commands",
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    dominantColor: "#f97316",
  },
]
